version: '3'
services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  order-service:
    image: ghcr.io/wussh/a433-microservices:order-service
    container_name: order-service
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: "amqp://rabbitmq:5672"

  shipping-service:
    image: ghcr.io/wussh/a433-microservices:shipping-service
    container_name: shipping-service
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: "amqp://rabbitmq:5672"

networks:
  app-network:
    driver: bridge
